module.exports = {
  config: {
    name: "am",
    aliases: ["animeme", "animememes", "animemes"],
    version: "1.0",
    author: "kshitiz",
    countDown: 20,
    role: 0,
    shortDescription: "get anime memes video",
    longDescription: "it will send you anime meme video",
    category: "anime",
    guide: "{p}{n}animeme",
  },

  sentVideos: [],

  onStart: async function ({ api, event, message }) {
    const senderID = event.senderID;

    const loadingMessage = await message.reply({
      body: "Loading random anime meme... Please wait! 🤡",
    });

    const link = [
      "https://drive.google.com/uc?export=download&id=1z1wVFu8utodxXac0MRI2uS9SZBRUTRmR",
      "https://drive.google.com/uc?export=download&id=1yrwwt5j50SkN8DPyQ8g56LFF6oMXVB2q",
      "https://drive.google.com/uc?export=download&id=1yNuWBm6g-bJ4h2ExJwmEeteUsDBDz3HR",
      "https://drive.google.com/uc?export=download&id=1xdk2fDIsV-dVvgUk7asw08X0WTIUwgTf",
      "https://drive.google.com/uc?export=download&id=1xRUu3Ae1eaZICYN5e690b8FWKJkIiq-w",
      "https://drive.google.com/uc?export=download&id=1xIlb7vTz3ZR5he8rW1lzS9xRPxZflFNz",
      "https://drive.google.com/uc?export=download&id=1xCFWG71h931gu-xb2-2vgiSscw_vVW3N",
      "https://drive.google.com/uc?export=download&id=1vtTafVbs4E0kkIW_8oVgcWLO9No4HrB-",
      "https://drive.google.com/uc?export=download&id=1va1zoPIvNsGvIPSrKYT3r11icjZk800J",
      "https://drive.google.com/uc?export=download&id=1t2BcA0dFL_KGm0_1SwRrts7XL9n0uFNn",
      "https://drive.google.com/uc?export=download&id=1-LsfOaiZXC7EZRcShJ2fKNCBIxfG0ozL",
      "https://drive.google.com/uc?export=download&id=1rZkRtK6HSHshSgnU9W-QcoIhhjtbO0ob",
      "https://drive.google.com/uc?export=download&id=1qvRc0PzDFfB4yIdVHMM0-rtNrfREoiTo",
      "https://drive.google.com/uc?export=download&id=1qqO6xOtOkEE3Q_S2E4DMdtQQ5xNdqq9E",
      "https://drive.google.com/uc?export=download&id=1q461o29fHBtMqk1mFc4EJqv6tMotjFIn",
      "https://drive.google.com/uc?export=download&id=1pEglKR6Fr91pyKTIP7NvY_aUU16Ql6-s",
      "https://drive.google.com/uc?export=download&id=1oxcxc4eeU3sRTmKgFs6WwVNayX0Pl-DI",
      "https://drive.google.com/uc?export=download&id=1okFs-a6HX7bvctGN3gVFECXhEmYSgESk",
      "https://drive.google.com/uc?export=download&id=1oX0K1wwcw06TfuRJZWT8Aq1WFqbn95vQ",
      "https://drive.google.com/uc?export=download&id=1nsVUvAsBWrKSltdqGhad3GJPLN8cZAFy",
      "https://drive.google.com/uc?export=download&id=1nYtn1skPk4vbYdVvjUoPJs4KriQYVkk_",
      "https://drive.google.com/uc?export=download&id=1mbbE3s69tefSRD8jqRlYhcJw3nzGlYcI",
      "https://drive.google.com/uc?export=download&id=1ko-heOBlSjmXnV3b8v-P_XoY5kwvuvqV",
      "https://drive.google.com/uc?export=download&id=1kLi0f_T2JJo21130jxNTiHxRqW70I5Z7",
      "https://drive.google.com/uc?export=download&id=1jQcG0PxK1-ArRwH9JwIqkBrRoSONy4As",
      "https://drive.google.com/uc?export=download&id=1ij6bW4uVvX81uZjBA19ecIy66oNRDwrr",
      "https://drive.google.com/uc?export=download&id=1i_Nnqr4O0AqjSnzK2DGMPesrGPwTic5D",
      "https://drive.google.com/uc?export=download&id=1gkMe6F6nyXb5jXg2lAltfzFotZEwIQZy",
      "https://drive.google.com/uc?export=download&id=1f_is5JJeKBWDekhCc0m_Epod98fd5FqC",
      "https://drive.google.com/uc?export=download&id=1fWY6Smt84f8kirVAcCeP9-XmQFCljR74",
      "https://drive.google.com/uc?export=download&id=1emhScnLfKiKk4Yr4-3EAbEqDbM32Kext",
      "https://drive.google.com/uc?export=download&id=1eMH01y65rSO-_PahGP0EYqN6qXj-4r_X",
      "https://drive.google.com/uc?export=download&id=1dcRj6_ahNQufVHsVJ4kkjVDs4ixcqV5k",
      "https://drive.google.com/uc?export=download&id=1dbwk8nfbjQ_bNJE-lrVAZEC4Lz_JuIZe",
      "https://drive.google.com/uc?export=download&id=1d_3xbuNV8in8ySE7L0bgWJGLfoZdpUrm",
      "https://drive.google.com/uc?export=download&id=1d3KS5IhWlujEL-BtHqdoUOA45VI3JSbK",
      "https://drive.google.com/uc?export=download&id=1cuLIp4L5xDNT8zFBkVmiIQkRvX6iw1eb",
      "https://drive.google.com/uc?export=download&id=1cbVtXoXaKjmBs4O-IuO6Zis9mu7noZV2",
      "https://drive.google.com/uc?export=download&id=1cY7oogNXOHlWVXLX9WE1lOV7oaQxf6rn",
      "https://drive.google.com/uc?export=download&id=1bns9KVdvPVW3A_18u93hVWTZ_zlS0Gst",
      "https://drive.google.com/uc?export=download&id=1_qad2iPPS2EjAxu8JlbEEfLo2Hgi7k_J",
      "https://drive.google.com/uc?export=download&id=1_lc9iir3OdBOp8jDr6uz-jS0XItoxRLz",
      "https://drive.google.com/uc?export=download&id=1_l1hcnwGsMSZMBSb-Lo6qzFB6ol99INx",
      "https://drive.google.com/uc?export=download&id=1Zy8_7KVvUc8gpUgjpqbFX2rnay9KG8On",
      "https://drive.google.com/uc?export=download&id=1YFZIfnH5jNHOpRAstD6V0MqgUB3pgtoJ",
      "https://drive.google.com/uc?export=download&id=1XJcbTS269GvMhq1cpq6M2W4iRTH_Sln-",
      "https://drive.google.com/uc?export=download&id=1Wz4e3ujd5pXb5Bg3KaIGRql0Nwpz5WaD",
      "https://drive.google.com/uc?export=download&id=1Wnh3OKcu9rkvuT8yla3gkpMymzOjEXEn",
      "https://drive.google.com/uc?export=download&id=1WjU-LCwBYuU7uWOso